### PR TITLE
BookingSchedule Model implementation and Booking Model updated

### PR DESCRIPTION
**Pull request by jmshltt**

### CODE REVIEW

**Review by M-Harty21 — APPROVED** [review]

**Review by JojoMojo-svg — APPROVED** [review]

**Comment by jmshltt** [comment]
Task linked: [CU-4hb7wh Create BookingSchedule table models](https://app.clickup.com/t/4hb7wh)

**Comment by jmshltt** [comment]
Task linked: [CU-4hb7xp Create BookingSchedule Repository](https://app.clickup.com/t/4hb7xp)

**Comment by jmshltt** [comment]
Task linked: [CU-4hb7z1 Create BookingSchedule Context](https://app.clickup.com/t/4hb7z1)

**Comment by jmshltt** [comment]
Task linked: [CU-4hb816 Fix Booking Model and Attributes](https://app.clickup.com/t/4hb816)

**Pull request merged**
